name: Deploy Github Package
on:
  release:
    types:
      - 'created'
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: Maven Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
             ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Github Maven Deploy
      run:|
         
	 git config --global user.email "girish.mahajan@aiocdawacs.com"
	 git config --global user.name "girishaiocdawacs"
         mvn --settings settings.xml -B clean package release:prepare release:perform -DskipTests=true
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CLOUD_PROJECT: ${{secrets.GKE_PROJECT}}
        GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GKE_SA_KEY}}
      
